-- Contract groups: a named layer between an employee and their contracts
-- within a project. Every contract belongs to exactly one group; payments
-- (contract_transaction) link to a group.
create table contract_group (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  project_id bigint not null references project(id),
  person_id bigint not null references person(id),
  name varchar not null
);

alter table contract add column group_id bigint references contract_group(id);

-- Backfill: one default group per (project, person) pair
insert into contract_group (project_id, person_id, name)
select distinct project_id, person_id, 'Հիմնական' from contract;

update contract c
set group_id = g.id
from contract_group g
where g.project_id = c.project_id and g.person_id = c.person_id;

alter table contract alter column group_id set not null;

-- Payments link to groups; legacy per-contract links stay in contact_id.
-- New rows may carry only group_id, so contact_id becomes nullable
-- (it was accidentally an identity column — drop that first).
alter table contract_transaction alter column contact_id drop identity if exists;
alter table contract_transaction alter column contact_id drop not null;
alter table contract_transaction add column group_id bigint references contract_group(id);

update contract_transaction ct
set group_id = c.group_id
from contract c
where c.id = ct.contact_id and ct.group_id is null;
