-- Price history per contract line: one row per saved price state.
-- The first row is the creation price; each later row is a change.
create table contract_price_history (
  id bigint generated by default as identity primary key,
  contract_id bigint not null references contract(id) on delete cascade,
  price float8,
  total float8 not null,
  changed_at timestamptz not null default now()
);
create index contract_price_history_contract_idx on contract_price_history(contract_id);

-- Seed with the current state of every existing contract at its creation date
insert into contract_price_history (contract_id, price, total, changed_at)
select id, price, total, created_at from contract;
