-- Ծավալաթերթ (bill of quantities): one sheet per project, extracted from XLSX
-- by the AI; Կատարողական (completion acts) record how much of each row is done.
create table volume_sheet (
  id bigint generated by default as identity primary key,
  project_id bigint not null unique references project(id) on delete cascade,
  file_name text,
  created_at timestamptz not null default now()
);

create table volume_sheet_row (
  id bigint generated by default as identity primary key,
  sheet_id bigint not null references volume_sheet(id) on delete cascade,
  seq int not null,
  kind text not null default 'item', -- 'group' | 'subgroup' | 'item'
  number text,
  code text,
  name text not null,
  unit text,
  qty float8,
  price float8
);
create index volume_sheet_row_sheet_idx on volume_sheet_row(sheet_id, seq);

create table completion_doc (
  id bigint generated by default as identity primary key,
  sheet_id bigint not null references volume_sheet(id) on delete cascade,
  doc_no int not null,
  created_at timestamptz not null default now()
);

create table completion_doc_row (
  doc_id bigint not null references completion_doc(id) on delete cascade,
  row_id bigint not null references volume_sheet_row(id) on delete cascade,
  qty float8 not null,
  primary key (doc_id, row_id)
);

-- Կատարողական rows record the actual price used in the act
alter table completion_doc_row add column price float8;
